---
title: "Exercises on chapter 5: Statistical inference"
author: "Lieven Clement and Jeroen Gilis"
date: "statOmics, Ghent University (https://statomics.github.io)"
output:
    html_document:
      code_download: true    
      theme: cosmo
      toc: true
      toc_float: true
      highlight: tango
      number_sections: true
---

On the second day of the "Practical Statistics for the Life Sciences (2021)" 
course, we will have three exercises on statistical, based on different 
datasets:


# The captopril dataset:

The captopril dataset holds information on a small experiment with 15 patients 
that have increased blood pressure values. More specifically, for each patient 
we will have four values; one value for systolic blood pressure and one for 
diastolyic, both before and after treating the patient with a drug named 
captopril.

In this tutorial on data exploration, you will learn how to perform hypothesis
testing with data from paired experimental designs.

- Exercise: [Exercise1](./05_1_captopril.html)
- Data path: https://raw.githubusercontent.com/statOmics/PSLS21/data/captopril.txt"

---

# The armpit dataset:

Smelly armpits are not caused by sweat, itself. The smell is caused by specific 
micro-organisms belonging to the group of Corynebacterium spp. that metabolise 
sweat. Another group of abundant bacteria are the Staphylococcus spp., which do
not metabolise sweat in smelly compounds.

The CMET-groep at Ghent University does research on transplanting the armpit 
microbiome to help people with smelly armpits. To test the effect of 
transplanting the microbiome, they conducted an experiment on two groups 
of volunteers: one group was treated with a placebo, while the other had a 
microbiome transplant. The goal was to find whether or not the relative 
abundance  Staphylococcus spp. in the microbiome of the armpit is significantly 
different between subjects treated with the placebo and subjects treated with a 
microbial transplant.

In this tutorial, you will use your acquired skills on hypothesis testing to 
test if the microbial transplant has helped in decreasing the (average) relative 
bundance Staphylococcus spp. in the microbiome of the armpit.

- Exercise: [Exercise2](./05_2_armpit.html)
- Data path: https://raw.githubusercontent.com/statOmics/PSLS21/data/armpit.csv"

---

# The Cuckoo dataset:

The common cuckoo does not build its own nest: it prefers to lay its eggs in 
another birds' nest. It is known, since 1892, that the type of cuckoo bird eggs 
are different between different locations. In a study from 1940, it was shown 
that cuckoos return to the same nesting area each year, and that they always 
pick the same bird species to be a "foster parent" for their eggs.

Over the years, this has lead to the development of geographically determined 
subspecies of cuckoos. These subspecies have evolved in such a way that their 
eggs look as similar as possible as those of their foster parents.

The cuckoo dataset contains information on 120 Cuckoo eggs, obtained from 
randomly selected "foster" nests. The researchers want to test if the type of 
foster parent has an effect on the average length of the cuckoo eggs. 

- Exercise: [Exercise3](./05_3_cuckoo.html)
- Data path: https://raw.githubusercontent.com/statOmics/PSLS21/data/Cuckoo.txt







