---
title: "Exercises on chapter 7: ANOVA"
author: "Lieven Clement and Jeroen Gilis"
date: "statOmics, Ghent University (https://statomics.github.io)"
output:
    html_document:
      code_download: true    
      theme: cosmo
      toc: true
      toc_float: true
      highlight: tango
      number_sections: true
---

On the third day of the "Practical Statistics for the Life Sciences (2021)" 
course, we will have three tutorials on ANOVA, based on different datasets:


# Fish tank dataset

In this experiment, 96 fish (dojofish, goldfish and zebrafish)
were placed separately in a tank with two liters of water and
a certain dose (in mg) of the poison EI-43,064. The resistance
of the fish against the poison was measured as the amount of
minutes the fish survived after being exposed to the poison (`Surv_time`, in
minutes). Additionally, the weight of each fish was measured.

In this tutorial session we will focus on Dojofish, and we will model the 
survival time in function of the poison dose while correcting for the weight of 
the fish. 

1. We will first analyse the survival data by only considering the dose as an
explanatory variable for survival time

2. Next we will model the survival data with and **additive model** for dose and 
weight

- Exercise: [Exercise1](./08_1_poison1.html)
- Data path: https://raw.githubusercontent.com/statOmics/PSLS21/data/freshweight_lettuce.txt

---

# The cuckoo dataset 

The common cuckoo does not build its own nest: it prefers to lay its eggs in 
another birds' nest. It is known, since 1892, that the type of cuckoo bird eggs 
are different between different locations. In a study from 1940, it was shown 
that cuckoos return to the same nesting area each year, and that they always 
pick the same bird species to be a "foster parent" for their eggs.

Over the years, this has lead to the development of geographically determined 
subspecies of cuckoos. These subspecies have evolved in such a way that their 
eggs look as similar as possible as those of their foster parents.

The cuckoo dataset contains information on 120 Cuckoo eggs, obtained from 
randomly selected "foster" nests. The researchers want to test if the type of 
foster parent has an effect on the average length of the cuckoo eggs.

- Exercise: [Exercise3](./07_2_cuckoo.html)
- Data path: https://raw.githubusercontent.com/statOmics/PSLS21/data/Cuckoo.txt

---

# The NHANES dataset:

The National Health and Nutrition Examination Survey (NHANES) contains data 
that has been collected since 1960. For this tutorial, we will make use of the 
data that was collected  between 2009 and  2012, for 10.000 U.S. civilians. 
The dataset contains a large number of physical, demographic, nutritional and 
life-style-related parameters.

We want to test whether or not the mean systolic blood pressure value 
(take column `BPSys1`) is equal between the five self-reported health 
categories. To this end, we will use an ANOVA analysis.

- Exercise: [Exercise3](./07_3_NHANES.html)
- Data path: https://raw.githubusercontent.com/statOmics/PSLS21/data/NHANES.csv


